# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-02 17:11


from django.db import migrations, models
import taxonomy.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20161129_1827'),
        ('curricula', '0004_change_prior_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='taxonomy',
            field=taxonomy.managers.TaxonomyTaggableManager(help_text='A comma-separated list of tags.', through='taxonomy.Taxonified', to='taxonomy.TaxonomyTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='taxonomy',
            field=taxonomy.managers.TaxonomyTaggableManager(help_text='A comma-separated list of tags.', through='taxonomy.Taxonified', to='taxonomy.TaxonomyTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='unit',
            name='taxonomy',
            field=taxonomy.managers.TaxonomyTaggableManager(help_text='A comma-separated list of tags.', through='taxonomy.Taxonified', to='taxonomy.TaxonomyTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='eras',
            field=models.ManyToManyField(blank=True, to='edumetadata.HistoricalEra'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='grades',
            field=models.ManyToManyField(blank=True, to='edumetadata.Grade'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='grouping_types',
            field=models.ManyToManyField(blank=True, to='curricula.GroupingType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='learner_groups',
            field=models.ManyToManyField(blank=True, to='curricula.LearnerGroup'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='materials',
            field=models.ManyToManyField(blank=True, to='curricula.Material'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='physical_space_types',
            field=models.ManyToManyField(blank=True, to='curricula.PhysicalSpaceType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='plugin_types',
            field=models.ManyToManyField(blank=True, to='curricula.PluginType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='prior_activities',
            field=models.ManyToManyField(blank=True, to='curricula.Activity', verbose_name=b'Recommended Prior Activities'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='secondary_content_types',
            field=models.ManyToManyField(blank=True, to='edumetadata.AlternateType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='skills',
            field=models.ManyToManyField(blank=True, to='curricula.Skill'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='standards',
            field=models.ManyToManyField(blank=True, to='curricula.Standard'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='edumetadata.Subject', verbose_name=b'Subjects and Disciplines'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='teaching_approaches',
            field=models.ManyToManyField(blank=True, to='curricula.TeachingApproach'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='teaching_method_types',
            field=models.ManyToManyField(blank=True, to='curricula.TeachingMethodType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tech_setup_types',
            field=models.ManyToManyField(blank=True, to='curricula.TechSetupType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tips',
            field=models.ManyToManyField(blank=True, to='curricula.Tip', verbose_name=b'Tips & Modifications'),
        ),
        migrations.AlterField(
            model_name='activityrelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[(b'Add this', b'Add this'), (b'Content Footer', b'Content Footer'), (b'key_image', b'Key Image'), (b'Model Student Work', b'Model of Student Work'), (b'Page footer', b'Page footer'), (b'Pictures of Practice', b'Pictures of Practice'), (b'resource_carousel', b'Resource Carousel (old)'), (b'resource_carousel_slide', b'Resource Carousel Slide'), (b'Right Rail Primary', b'Right Rail Primary'), (b'Right Rail Secondary', b'Right Rail Secondary')], help_text="A generic text field to tag a relation, like 'primaryphoto'.", max_length=200, null=True, verbose_name='Relation Type'),
        ),
        migrations.AlterField(
            model_name='ideacategory',
            name='eras',
            field=models.ManyToManyField(blank=True, to='edumetadata.HistoricalEra'),
        ),
        migrations.AlterField(
            model_name='ideacategory',
            name='grades',
            field=models.ManyToManyField(blank=True, to='edumetadata.Grade'),
        ),
        migrations.AlterField(
            model_name='ideacategory',
            name='secondary_content_types',
            field=models.ManyToManyField(blank=True, to='edumetadata.AlternateType'),
        ),
        migrations.AlterField(
            model_name='ideacategory',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='edumetadata.Subject', verbose_name=b'Subjects and Disciplines'),
        ),
        migrations.AlterField(
            model_name='ideacategoryrelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[(b'Add this', b'Add this'), (b'Content Footer', b'Content Footer'), (b'key_image', b'Key Image'), (b'Model Student Work', b'Model of Student Work'), (b'Page footer', b'Page footer'), (b'Pictures of Practice', b'Pictures of Practice'), (b'resource_carousel', b'Resource Carousel (old)'), (b'resource_carousel_slide', b'Resource Carousel Slide'), (b'Right Rail Primary', b'Right Rail Primary'), (b'Right Rail Secondary', b'Right Rail Secondary')], help_text="A generic text field to tag a relation, like 'primaryphoto'.", max_length=200, null=True, verbose_name='Relation Type'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='eras',
            field=models.ManyToManyField(blank=True, to='edumetadata.HistoricalEra'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grades',
            field=models.ManyToManyField(blank=True, to='edumetadata.Grade'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.ManyToManyField(blank=True, help_text=b'This field is for additional, lesson-level materials a\n        teacher will need to provide; for example, new materials needed in\n        order to conduct the lesson-level assessment. Do not repeat activity-\n        specific materials.', to='curricula.Material'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='physical_space_types',
            field=models.ManyToManyField(blank=True, to='curricula.PhysicalSpaceType'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='plugin_types',
            field=models.ManyToManyField(blank=True, to='curricula.PluginType'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='prior_lessons',
            field=models.ManyToManyField(blank=True, to='curricula.Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='secondary_content_types',
            field=models.ManyToManyField(blank=True, to='edumetadata.AlternateType'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='edumetadata.Subject', verbose_name=b'Subjects and Disciplines'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tech_setup_types',
            field=models.ManyToManyField(blank=True, to='curricula.TechSetupType'),
        ),
        migrations.AlterField(
            model_name='lessonrelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[(b'Add this', b'Add this'), (b'Content Footer', b'Content Footer'), (b'key_image', b'Key Image'), (b'Model Student Work', b'Model of Student Work'), (b'Page footer', b'Page footer'), (b'Pictures of Practice', b'Pictures of Practice'), (b'resource_carousel', b'Resource Carousel (old)'), (b'resource_carousel_slide', b'Resource Carousel Slide'), (b'Right Rail Primary', b'Right Rail Primary'), (b'Right Rail Secondary', b'Right Rail Secondary')], help_text="A generic text field to tag a relation, like 'primaryphoto'.", max_length=200, null=True, verbose_name='Relation Type'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='eras',
            field=models.ManyToManyField(blank=True, to='edumetadata.HistoricalEra'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='grades',
            field=models.ManyToManyField(blank=True, to='edumetadata.Grade'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='secondary_content_types',
            field=models.ManyToManyField(blank=True, to='edumetadata.AlternateType'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='edumetadata.Subject'),
        ),
        migrations.AlterField(
            model_name='unitrelation',
            name='relation_type',
            field=models.CharField(blank=True, choices=[(b'Add this', b'Add this'), (b'Content Footer', b'Content Footer'), (b'key_image', b'Key Image'), (b'Model Student Work', b'Model of Student Work'), (b'Page footer', b'Page footer'), (b'Pictures of Practice', b'Pictures of Practice'), (b'resource_carousel', b'Resource Carousel (old)'), (b'resource_carousel_slide', b'Resource Carousel Slide'), (b'Right Rail Primary', b'Right Rail Primary'), (b'Right Rail Secondary', b'Right Rail Secondary')], help_text="A generic text field to tag a relation, like 'primaryphoto'.", max_length=200, null=True, verbose_name='Relation Type'),
        ),
    ]
