# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-14 19:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0005_auto_20161202_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryidea',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='categoryidea',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
