# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-22 15:52


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0006_add_categoryidea_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='key_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_media.NGPhoto'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='key_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_media.NGPhoto'),
        ),
        migrations.AlterField(
            model_name='ideacategory',
            name='key_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_media.NGPhoto'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='key_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_media.NGPhoto'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='key_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_media.NGPhoto'),
        ),
    ]
