from django.conf.urls.defaults import *

urlpatterns = patterns('curricula.views',
    url(r'objectives/(?P<id>\d+)/$', 
        'learning_objectives',
        name='learning-objectives'),
    url(r'^lesson/(?P<slug>[-\w]*)/materials/$', 
        'lesson_detail', 
        {'template_name': 'curricula/fragments/materials.html'},
        name='lesson-materials'),
    url(r'^lesson/(?P<slug>[-\w]*)/preparation/$', 
        'lesson_detail', 
        {'template_name': 'curricula/fragments/preparation.html'},
        name='lesson-preparation'),
    url(r'background-information/(?P<id>\d+)/$', 
        'background_information',
        name='background-information'),
    url(r'get_breakout_terms/(?P<id>\d+)/$', 
        'get_breakout_terms',
        name='get-breakout-terms'),
)
